### ISSUE TITLE
Update discord.js version

### ISSUE THREAD

**Issue by Sidemen19** [Dorumin/Twinkle#32]
Discord.js v11 is coming to end of life soon, so some modifications will have to be made to Twinkle to update to v12.

[Here is a link](https://discordjs.guide/additional-info/changes-in-v12.html#commonly-used-methods-that-changed) with a list of methods and properties that need to be updated.

Summary of pretty much all that needs to be updated:
* User#displayAvatarURL --> User#displayAvatarURL() <sub><sup>(message.author.displayAvatarURL --> message.author.displayAvatarURL())</sub></sup>
* Guild#fetchMembers() --> GuildMemberManager#fetch() <sub><sup>(message.guild.fetchMembers() --> message.guild.members.fetch())</sub></sup>
* GuildMember#addRole() --> GuildMemberRoleManager#add() <sub><sup>(message.member.addRole() --> message.member.roles.add())</sub></sup>
* Client#ping --> WebSocketManager#ping <sub><sup>(this.bot.client.ping --> this.bot.client.ws.ping)</sub></sup>

\+ plus having to directly ask for cache on a manager before trying to use collection methods <sub><sup>(e.g. this.bot.client.users.get() --> this.bot.client.users.cache.get())</sub></sup>

**Comment by Dorumin** [comment]
This is no time for caution

v12 is deployed into master now, the future's in your hands now
